### ISSUE TITLE
Support for memcached?

### ISSUE THREAD

**Issue by ayacoo** [b13/graceful-cache#2]
Memcached is also addressed in the README, but is not present here as a class. Is that the way it is supposed to be?

**Comment by bmack** [comment]
We're currently in a very alpha state, building this extension for a specific use case and testing it. It may take another few weeks to go live, for this reason, this extension isn't really "ready" yet...

**Comment by bmack** [comment]
@ayacoo care to create a patch for this?

**Comment by ayacoo** [comment]
@bmack Sure! We don't have $this->connected in the MemcacheBackend. Is the try/catch variant enough for you?

**Comment by bmack** [comment]
yes
